fieldLayouts:
  66a99891-1a70-40da-a53d-a0ef5fd35d06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1765c65-2e8d-4f7d-b309-59bc1dc7e23d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d9a2cf7-87f6-42f8-b55d-5c0f0f57f1a4
        userCondition: null
handle: storiesListing
hasTitleField: true
name: 'Stories Listing'
section: de250fd7-8482-4148-93cc-656aca7f5580 # Stories Listing
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
