columnSuffix: null
contentColumnType: string
fieldGroup: 0ca69b71-6551-497b-af4b-cc9cc4fb8fcd # Home Page
handle: featuredStory
instructions: null
name: 'Featured Story'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Select a Story'
  showSiteMenu: true
  sources:
    - 'section:e5a98c90-afdd-43e8-943d-d3c7a15a2f10' # Stories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
