columnSuffix: null
contentColumnType: string
fieldGroup: c2a22434-2467-4802-ba70-1f9d0331931d # Common
handle: photo
instructions: null
name: Photo
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:dbd975c4-c434-4cd7-8146-06cdc86fdccb' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:dbd975c4-c434-4cd7-8146-06cdc86fdccb' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: 'Upload a Photo'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
