columnSuffix: null
contentColumnType: string
fieldGroup: 0ca69b71-6551-497b-af4b-cc9cc4fb8fcd # Home Page
handle: riders
instructions: null
name: Riders
searchable: false
settings:
  contentTable: '{{%matrixcontent_riders}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
