fieldLayouts:
  d54e641d-f697-412a-905a-47c0335dce04:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3933d639-57c2-4da8-9d0b-b74ac48469cf # Text Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5aae1d2a-df1b-4737-a9cc-55e378bbe25e
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: 5e893eb4-5813-4b21-b65e-84a163b0503a
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
