fieldLayouts:
  df045383-a73a-4f85-a326-31b3bd53302d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: feafa0b6-dd77-4f2b-b70a-f77e27853454 # Top Nav Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19717dfc-f12b-4bb0-99c5-0e5b9949bc2f
            userCondition: null
            warning: null
            width: 100
        name: Menus
        uid: 7c3c00f8-44d5-46fc-94ff-060b594e7ccb
        userCondition: null
handle: navigationMenu
name: 'Navigation Menu'
sortOrder: 1
