defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  621b7e3b-4418-4e95-8453-3c82a4b5eb60: # Craft 4 Demo
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
